/**
 * 关卡配置
 */


/** 关卡配置 */    // levelType 关卡类型: 1:成语 2:拼音 3:诗词  word: 题目内容 vacancy: 空缺位置 
export const LevelConfig = [
    {
        "levelType": 1,
        "word": "花团锦簇",
        "vacancy": 2,
        "correct": "锦",
        "wrong": "紧",
    },
    {
        "levelType": 1,
        "word": "画地为牢",
        "vacancy": 0,
        "correct": "画",
        "wrong": "划",
    },
    {
        "levelType": 1,
        "word": "垂头丧气",
        "vacancy": 3,
        "correct": "气",
        "wrong": "弃",
    },
    {
        "levelType": 1,
        "word": "弥天大谎",
        "vacancy": 0,
        "correct": "弥",
        "wrong": "迷",
    },
    {
        "levelType": 1,
        "word": "浑然一体",
        "vacancy": 0,
        "correct": "浑",
        "wrong": "混",
    },
    {
        "levelType": 1,
        "word": "急不可耐",
        "vacancy": 3,
        "correct": "耐",
        "wrong": "奈",
    },
    {
        "levelType": 1,
        "word": "见机行事",
        "vacancy": 1,
        "correct": "机",
        "wrong": "计",
    },
    {
        "levelType": 1,
        "word": "金碧辉煌",
        "vacancy": 1,
        "correct": "碧",
        "wrong": "壁",
    },
    {
        "levelType": 1,
        "word": "绵里藏针",
        "vacancy": 0,
        "correct": "绵",
        "wrong": "棉",
    },
    {
        "levelType": 1,
        "word": "人才辈出",
        "vacancy": 2,
        "correct": "辈",
        "wrong": "倍",
    },
    {
        "levelType": 1,
        "word": "假手于人",
        "vacancy": 2,
        "correct": "于",
        "wrong": "与",
    },
    {
        "levelType": 1,
        "word": "味同嚼蜡",
        "vacancy": 3,
        "correct": "蜡",
        "wrong": "腊",
    },
    {
        "levelType": 1,
        "word": "香消玉殒",
        "vacancy": 3,
        "correct": "殒",
        "wrong": "陨",
    },
    {
        "levelType": 1,
        "word": "心术不正",
        "vacancy": 1,
        "correct": "术",
        "wrong": "数",
    },
    {
        "levelType": 1,
        "word": "信口雌黄",
        "vacancy": 3,
        "correct": "黄",
        "wrong": "皇",
    },
    {
        "levelType": 1,
        "word": "秀外慧中",
        "vacancy": 2,
        "correct": "慧",
        "wrong": "蕙",
    },
    {
        "levelType": 1,
        "word": "兴师动众",
        "vacancy": 3,
        "correct": "众",
        "wrong": "重",
    },
    {
        "levelType": 1,
        "word": "轩然大波",
        "vacancy": 0,
        "correct": "轩",
        "wrong": "喧",
    },
    {
        "levelType": 1,
        "word": "喧宾夺主",
        "vacancy": 0,
        "correct": "喧",
        "wrong": "宣",
    },
    {
        "levelType": 1,
        "word": "学无止境",
        "vacancy": 3,
        "correct": "境",
        "wrong": "径",
    },
    {
        "levelType": 1,
        "word": "徇私舞弊",
        "vacancy": 0,
        "correct": "徇",
        "wrong": "循",
    },
    {
        "levelType": 1,
        "word": "杳无音信",
        "vacancy": 0,
        "correct": "杳",
        "wrong": "沓",
    },
    {
        "levelType": 1,
        "word": "耀武扬威",
        "vacancy": 2,
        "correct": "扬",
        "wrong": "昂",
    },
    {
        "levelType": 1,
        "word": "一见钟情",
        "vacancy": 2,
        "correct": "钟",
        "wrong": "终",
    },
    {
        "levelType": 1,
        "word": "衣锦还乡",
        "vacancy": 1,
        "correct": "锦",
        "wrong": "巾",
    },
    {
        "levelType": 1,
        "word": "引以为荣",
        "vacancy": 0,
        "correct": "引",
        "wrong": "隐",
    },
    {
        "levelType": 1,
        "word": "由浅入深",
        "vacancy": 0,
        "correct": "由",
        "wrong": "犹",
    },
    {
        "levelType": 1,
        "word": "游手好闲",
        "vacancy": 3,
        "correct": "闲",
        "wrong": "嫌",
    },
    {
        "levelType": 1,
        "word": "语无伦次",
        "vacancy": 2,
        "correct": "伦",
        "wrong": "轮",
    },
    {
        "levelType": 1,
        "word": "在劫难逃",
        "vacancy": 0,
        "correct": "在",
        "wrong": "再",
    },
    {
        "levelType": 1,
        "word": "执迷不悟",
        "vacancy": 0,
        "correct": "执",
        "wrong": "直",
    },
    {
        "levelType": 1,
        "word": "走投无路",
        "vacancy": 1,
        "correct": "投",
        "wrong": "头",
    },
    {
        "levelType": 1,
        "word": "财迷心窍",
        "vacancy": 3,
        "correct": "窍",
        "wrong": "窃",
    },
    {
        "levelType": 1,
        "word": "安贫乐道",
        "vacancy": 3,
        "correct": "道",
        "wrong": "到",
    },
    {
        "levelType": 1,
        "word": "无可奈何",
        "vacancy": 2,
        "correct": "奈",
        "wrong": "耐",
    },
    {
        "levelType": 3,
        "word": "不识庐山真面目,(下一句)",
        "vacancy": 1,
        "correct": "只缘身在此山中",
        "wrong": "只缘身在最高层",
    },
    {
        "levelType": 1,
        "word": "始终不渝",
        "vacancy": 3,
        "correct": "渝",
        "wrong": "逾",
    },
    {
        "levelType": 1,
        "word": "寒冬腊月",
        "vacancy": 2,
        "correct": "腊",
        "wrong": "蜡",
    },
    {
        "levelType": 2,
        "word": "循规蹈矩",
        "vacancy": 3,
        "correct": "jǔ",
        "wrong": "jù",
    },
    {
        "levelType": 2,
        "word": "模样",
        "vacancy": 0,
        "correct": "mú",
        "wrong": "mó",
    },
    {
        "levelType": 3,
        "word": "(上一句),年年知为谁生",
        "vacancy": 1,
        "correct": "念桥边红药",
        "wrong": "二十四桥仍在",
    },
    {
        "levelType": 1,
        "word": "蜂拥而至",
        "vacancy": 1,
        "correct": "拥",
        "wrong": "涌",
    },
    {
        "levelType": 3,
        "word": "抽刀断水水更流,(下一句)",
        "vacancy": 1,
        "correct": "举杯消愁愁更愁",
        "wrong": "举杯消愁愁又愁",
    },
    {
        "levelType": 1,
        "word": "细枝末节",
        "vacancy": 3,
        "correct": "节",
        "wrong": "截",
    },
    {
        "levelType": 1,
        "word": "血气方刚",
        "vacancy": 3,
        "correct": "刚",
        "wrong": "钢",
    },
    {
        "levelType": 2,
        "word": "审度",
        "vacancy": 0,
        "correct": "duó",
        "wrong": "dù",
    },
    {
        "levelType": 2,
        "word": "露怯",
        "vacancy": 0,
        "correct": "lòu",
        "wrong": "lù",
    },
]


